micronaut:
  application:
    name: cheesecake
  security:
    authentication: session
    endpoints:
      login:
        path: /auth/login
      logout:
        path: /auth/logout
    intercept-url-map:
      - pattern: /auth/register
        http-method: POST
        access:
          - isAnonymous()
      - pattern: /auth/session
        http-method: GET
        access:
          - isAuthenticated()
      - pattern: /api/**
        access:
          - isAuthenticated()
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cheesecake_dev
    driverClassName: org.postgresql.Driver
    username: cheesecaker
    password: 'cheesecaker'
    schema-generate: none
    dialect: POSTGRES
jackson:
  serialization-inclusion: non_absent