micronaut:
  application:
    name: cheesecake
  security:
    authentication: session
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cheesecake_dev
    driverClassName: org.postgresql.Driver
    username: cheesecaker
    password: 'cheesecaker'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
